import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:provider/provider.dart'; // For state management (theme)

import 'firebase_options.dart'; // This file is crucial and generated by FlutterFire
import 'sign_in_page.dart';
import 'weather_home.dart'; // This import now also brings in ThemeProvider

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase asynchronously
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Load the initial theme preference from SharedPreferences using ThemeProvider from weather_home.dart
  final themeProvider = ThemeProvider(await ThemeProvider.getInitialThemeMode());

  runApp(
    // Provide the ThemeProvider to the entire application
    ChangeNotifierProvider<ThemeProvider>(
      create: (_) => themeProvider,
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Watch for theme changes from the ThemeProvider
    final themeProvider = Provider.of<ThemeProvider>(context);

    return MaterialApp(
      title: 'Forecast First Aid',
      debugShowCheckedModeBanner: false, // Set to false for production
      theme: themeProvider.currentTheme, // Apply the current theme (light or dark)

      // Use StreamBuilder to react to Firebase Authentication state changes
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(), // Listen to auth state
        builder: (context, snapshot) {
          // If the connection to the auth stream is active
          if (snapshot.connectionState == ConnectionState.active) {
            User? user = snapshot.data; // Get the current user (or null if signed out)

            if (user == null) {
              // No user is signed in, show the SignInPage
              return const SignInPage();
            } else {
              // A user is signed in, show the main WeatherApp
              return const WeatherApp();
            }
          }
          // While waiting for the authentication state, show a loading indicator
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(),
            ),
          );
        },
      ),
    );
  }
}